services:
  vulnerable-app:
    build:
      context: ./vulnerable_app
    container_name: cookievigil-vulnerable-app
    ports:
      - "5000:5000"
    networks:
      - cookievigil-lab

  cookievigil:
    build:
      context: .
    container_name: cookievigil-scanner
    depends_on:
      - vulnerable-app
    networks:
      - cookievigil-lab
    volumes:
      - ./reports:/app/reports
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      [
        "http://vulnerable-app:5000/set-bad-cookies",
        "--force-https-context",
        "--format",
        "all",
        "--fail-on",
        "none"
      ]

networks:
  cookievigil-lab:
    driver: bridge
